# eot.rb

# require 'multi_xml'
require 'addressable/uri'
#require 'celes'
require_relative 'eot/helio'
require 'json'
require 'rest-client'

require 'date'

require_relative 'eot/solar_strings'
require_relative 'eot/angles'
require_relative 'eot/constants'
require_relative 'eot/deltas'
require_relative 'eot/delta_times'
require_relative 'eot/delta_times_jd'
require_relative 'eot/geo_lat_lng_smt'
require_relative 'eot/init'
require_relative 'eot/jd_times'
require_relative 'eot/mean_angles'
require_relative 'eot/string_formatters'
require_relative 'eot/time_displays'
require_relative 'eot/times'
require_relative 'eot/trigonometric'
require_relative 'eot/true_angles'
require_relative 'eot/utilities'
require_relative 'eot/version'
