# eot.rb

# require 'multi_xml'
require 'addressable/uri'
#require 'celes'
require 'eot/helio'
require 'json'
require 'rest-client'

require 'date'

require 'eot/angle_displays'
require 'eot/angles'
require 'eot/constants'
require 'eot/deltas'
require 'eot/delta_times'
require 'eot/delta_times_jd'
require 'eot/geo_lat_lng_smt'
require 'eot/init'
require 'eot/jd_times'
require 'eot/mean_angles'
require 'eot/time_displays'
require 'eot/times'
require 'eot/trigonometric'
require 'eot/true_angles'
require 'eot/utilities'
require 'eot/version'
